version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  java-app:
    build: .
    container_name: java_app_container
    depends_on:
      - db
    environment:
      DATABASE_URL: "jdbc:mysql://db:3306/mydatabase"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "rootpassword"

